name: Iange scan

on: 
   workflow_dispatch:

permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      security-events: write

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Run Terrascan
      #   id: terrascan
      #   uses: tenable/terrascan-action@main
      #   with:
      #      iac_type: 'terraform'
      #      iac_version: 'v14'
      #      policy_type: 'aws'
      #      only_warn: true
      #      sarif_upload: true
      #      #non_recursive:
      #      #iac_dir:
      #      #policy_path:
      #      #skip_rules:
      #      #config_path:
      #      #webhook_url:
      #      #webhook_token:
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
           sarif_file: terrascan.sarif

      - name: Create config.tf file
        run: |
          cat <<EOL > config.tf

          terraform {

            backend "s3" {

            bucket  =  "shaft-bucket"

            encrypt = true
            
            dynamodb_table = "lock-state"

            key 	= "stg_stateterraform_state.tfstate"

            region  = "ap-south-1"

            }
            required_providers {

            aws = {

              source  = "hashicorp/aws"

              version = "~> 5.23.1"

            }

            }

          }
          provider "aws" {

            region = "ap-south-1"

          }

          EOL

          echo "Terraform configuration file created: config.tf"
       
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
           aws-access-key-id: ${{ secrets.STG_AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.STG_AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4
   
      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: "shaft-bucket"
          AWS_BUCKET_KEY_NAME: "s-terraform"
        run: terraform init -upgrade 
   
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
   
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -refresh=false  -no-color -out out.plan
        continue-on-error: false
   
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
